# Generated by Django 2.2.3 on 2019-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20190720_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
